#spring.application.name=image-editor
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/editor
    username: root
    password: hmax0705
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 50000MB

server:
  port: 9000
  tomcat:
    max-http-form-post-size: 50000MB

jwt:
  secret: jh354ghjg13hjhgiuyib4n84fewfe812gffh32
  lifetime: 300m
logging:
  level:
    root: info
